#!/sh
# Get staged files but explicitly exclude node_modules, package-lock, and images
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(js|ts|json|env|yml|yaml|md|txt|sh)$' | grep -v 'node_modules/' | grep -v 'package-lock.json')

if [ -z "$STAGED_FILES" ]; then
    exit 0
fi

node secret_scanner.js $STAGED_FILES
